---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-team
spec:
  interval: 1m0s
  ref:
    branch: dev-team
  secretRef:
    name: flux-system
  url: ssh://git@github.com/edwardsuwirya/finalproject-gitops
