apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stakater
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: 'v1.0.42'
      sourceRef:
        kind: HelmRepository
        name: stakater
      interval: 1m