apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - istio-gateway.yaml
  - be-virtual-service.yaml
  - fe-virtual-service.yaml
  - certificate.yaml
  - cluster-issuer.yaml